SPACESHIP_RANGER_PREFIX="${SPACESHIP_RANGER_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_RANGER_SUFFIX="${SPACESHIP_RANGER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_RANGER_SYMBOL="${SPACESHIP_RANGER_SYMBOL="⚠️  "}"
SPACESHIP_RANGER_TEXT="${SPACESHIP_WIP_TEXT="Nested instances!"}"
SPACESHIP_RANGER_COLOR="${SPACESHIP_WIP_COLOR="yellow"}"

spaceship_ranger() {
    [[ $SPACESHIP_RANGER_SHOW == false ]] && return

    spaceship::exists ranger || return
    [[ -z $RANGER_LEVEL ]] && return

    spaceship::section \
      "$SPACESHIP_RANGER_COLOR" \
      "$SPACESHIP_RANGER_PREFIX" \
      "$SPACESHIP_RANGER_SYMBOL" \
      "$SPACESHIP_RANGER_TEXT" \
      "$SPACESHIP_RANGER_SUFFIX"
}
