[colors.bright]
black = "0x555555"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xffffff"
yellow = "0xf1fa8c"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[font]
size = 15.0

[font.normal]
family = "Hack Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[scrolling]
history = 20000
multiplier = 0

[shell]
args = ["new", "-A"]
program = "/opt/homebrew/opt/tmux/bin/tmux"

[window]
startup_mode = "Maximized"
